version: "3.0"

services:
  supervisor: 
    container_name: ros_supervisor
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    environment:
      - "PROJECT_NAME=ros_docker"
      - "SUPERVISOR_DOCKER_PROJECT_PATH=/ros_docker/"
      - "SUPERVISOR_DOCKER_COMPOSE_FILE=docker-compose.yml"
      - "SUPERVISOR_CONFIG_FILE=ros-supervisor.yml"
      - "GITHUB_ACCESS_TOKEN=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"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/khoa/research/code/github/ros_docker:/ros_docker
      - /home/khoa/research/code/github/ros-supervisor:/ros-supervisor
      - supervisor:/supervisor

volumes:
  supervisor: