version: "3.0"

services:
  supervisor: 
    container_name: ros_supervisor
    hostname: ros_supervisor
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    environment:
      - HOSTMACHINE_HOSTNAME=${HOSTNAME}
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/tmp/etc/hosts:rw
      - supervisor:/supervisor
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8080/health/liveness --silent --include --header 'Content-Type: application/json' --request 'GET' || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      supervisor:
        ipv4_address: 172.21.0.2

volumes:
  supervisor:

networks:
  supervisor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1