version: "3.0"

services:
  supervisor: 
    container_name: ros_supervisor
    hostname: ros_supervisor
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/khoa/research/code/github/ros-supervisor:/ros_supervisor
      - supervisor:/supervisor
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8080/health/liveness --silent --include --header 'Content-Type: application/json' --request 'GET' || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      supervisor:
        ipv4_address: 172.21.0.2

volumes:
  supervisor:

networks:
  supervisor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
