version: "3.0"

services:
  supervisor: 
    container_name: ros_supervisor
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SUPERVISOR_DOCKER_PROJECT_PATH=/ros_docker/"
      - "SUPERVISOR_DOCKER_COMPOSE_FILE=docker-compose.yml"
      - "SUPERVISOR_CONFIG_FILE=ros-supervisor.yml"
      - "GITHUB_ACCESS_TOKEN=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"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock