# The container that we build the project in
FROM golang:1.17 AS build

RUN apt-get update \
  && apt-get install -y --no-install-recommends make git

COPY . /ros-supervisor/
RUN cd /ros-supervisor/ && go mod download && go build

WORKDIR /
CMD [ "bash", "-c", "tail -f /dev/null" ]
