# The container that we build the project in
FROM golang:1.17 AS build

RUN apt-get update \
  && apt-get install -y --no-install-recommends make git

RUN mkdir /ros_project
RUN sysctl -w net.ipv4.ping_group_range="0 2147483647"

WORKDIR /
CMD [ "bash", "-c", "tail -f /dev/null" ]
